### ISSUE TITLE
Kebechet update

### ISSUE THREAD

**Issue by codificat** [thoth-station/ps-ip#17]
Hey, Kebechet!

Update my dependencies, please.

Closes #16

**Comment by codificat** [comment]
This one failed as in https://github.com/thoth-station/support/issues/140

```
2021-11-25 11:48:51,704   1 INFO     kebechet:68: Kebechet version: '1.6.6'
2021-11-25 11:48:51,705   1 DEBUG    kebechet:72: Debug mode turned on
2021-11-25 11:48:52,297   1 INFO     kebechet.utils:147: host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv
overlays_dir: overlays

runtime_environments:
  - name: ps-ip-ifd
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

managers:
  - name: info
  - name: version
    configuration:
      maintainers:
        - goern
        - harshad16
        - pacospace
        - eldritchjs
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
  - name: thoth-advise
    configuration:
      labels: [bot]

2021-11-25 11:48:52,324   1 INFO     kebechet:194: Running manager 'info' for 'thoth-station/ps-ip'
2021-11-25 11:48:53,184   1 INFO     kebechet.managers.info.info:51: No issue to report to, exiting
2021-11-25 11:48:53,184   1 INFO     kebechet:194: Running manager 'version' for 'thoth-station/ps-ip'
2021-11-25 11:48:54,082   1 INFO     kebechet:194: Running manager 'thoth-advise' for 'thoth-station/ps-ip'
2021-11-25 11:48:54,951   1 ERROR    kebechet:212: An error occurred during run of manager {'configuration': {'labels': ['bot']}} <class 'kebechet.managers.thoth_advise.thoth_advise.ThothAdviseManager'> for 'thoth-station/ps-ip', skipping
Traceback (most recent call last):
  File "/home/user/kebechet/kebechet_runners.py", line 210, in run
    instance.run(**manager_configuration)
  File "/home/user/kebechet/managers/thoth_advise/thoth_advise.py", line 312, in run
    self._close_advise_issues4users_lacking_perms()
  File "/home/user/kebechet/managers/thoth_advise/thoth_advise.py", line 258, in _close_advise_issues4users_lacking_perms
    permitted_users = self._get_users_with_permission()
  File "/home/user/kebechet/managers/thoth_advise/thoth_advise.py", line 250, in _get_users_with_permission
    self.service.user.get_username()
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/abstract.py", line 63, in wrapper
    return function(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/services/github/user.py", line 26, in get_username
    return self.service.github.get_user().login
AttributeError: 'NoneType' object has no attribute 'get_user'
2021-11-25 11:48:58,780   1 INFO     kebechet:245: Finished management for 'thoth-station/ps-ip'
```

It's not nice that this fails silently, but this should be addressed in the referenced issue.

The `close_advise_issues4users_lacking_perms()` in the stack trace suggests it's because I'm not in this repo's [maintainers](https://github.com/thoth-station/ps-ip/blob/bc738c7b3617be9cbf9ae8886f5d5f3a6ef9f163/.thoth.yaml#L18-L22).
Hopefully this should work if initiated by a maintainer.
/close
